spring.application.name=auctionhub
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/auctionhub
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Configuration (CHANGE THIS IN PRODUCTION!)
jwt.secret.b64=${JWT_SECRET_B64:vK8sP2mN9xR4wT6yQ3jL7aD1fH5cG0bE2iU8oZ4nM6s=}


STRIPE.WEBHOOK.SECRET=${STRIPE_WEBHOOK_SECRET}

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092

# Kafka Consumer Config
spring.kafka.consumer.group-id=auction-hub-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.auctionhub.auctionhub.events.dto
