spring.application.name=auctionhub
spring.docker.compose.enabled=false
spring.datasource.url=jdbc:postgresql://localhost:5432/auctionhub
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Configuration (CHANGE THIS IN PRODUCTION!)
JWT_SECRET_B64=${JWT_SECRET_B64:vK8sP2mN9xR4wT6yQ3jL7aD1fH5cG0bE2iU8oZ4nM6s=}


STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}

STRIPE.WEBHOOK.SECRET=${STRIPE_WEBHOOK_SECRET}
